name: Google Ping Barlagy


on:
  push:
    branches: [ "main" ]  
  workflow_dispatch:     

jobs:
  ping_isi:
    runs-on: ubuntu-latest  

    steps:
      - name: Google-a HTTP Soragy Ugratmak
        run: |
          echo "Google web sahypasyna baglanyşyk barlanýar..."
          curl -I https://www.google.com
